# The current version of the config schema
version: 1
git_protocol: https
editor: nvim
prompt: enabled
prefer_editor_prompt: disabled
pager:
aliases:
    co: pr checkout
http_unix_socket:
browser:
color_labels: disabled
accessible_colors: disabled
accessible_prompter: disabled
spinner: enabled
